# Set nginx base image
FROM nginx:1.13-alpine

# Copy custom configuration file from the current directory
COPY ./nginx/nginx.conf /etc/nginx/nginx.conf
ADD nginx/secret_key.conf /etc/nginx/main.d/secret_key.conf
ADD nginx/gzip_max.conf /etc/nginx/conf.d/gzip_max.conf

EXPOSE 8080

RUN mkdir -p /home/app/webapp/public
COPY ./dist/client /home/app/webapp/public
